region                    = "eu-west-3"
project                   = "lims"
environment               = "dev"
vpc_cidr                  = "10.0.0.0/16"
azs                       = ["eu-west-3a", "eu-west-3b"]
app_image                 = "nginx:latest"
app_port                  = 80
app_cpu                   = 256
app_memory                = 512
desired_count             = 2
db_name                   = "lims"
db_username               = "limsadmin"
db_instance_class         = "db.t3.small"
db_allocated_storage      = 20
db_multi_az               = false
db_secret_name            = "lims/db/main"
s3_bucket_name            = "lims-static-assets"
hosted_zone_name          = "lims.example.com"
geo_locations             = ["EU", "NA", "AS", "OC", "SA", "AF"]
cloudfront_waf_rate_limit = 2000
api_stage_name            = "v1"
enable_authorizer         = true
